#!/usr/bin/python3

#cc_a_library(
#		name = "gtest_main",
#		libname = "output/amd64-clang-none/obj/aos/build/libgtest.a",
#		cflags = ["-Ioutput/downloaded/gtest-1.6.0-p2/include"],
#)
#
#pkg_config(name = "gtk+-3.0")

#cc_a_library(
#    name = "libjpeg",
#    libname = "output/compiled-amd64/jpeg-8d/.libs/libjpeg.a",
#)

#cc_system_library(name = "libjpeg", lib = 'jpeg')




